# /opt/scalp/config/indicators.yml
rsi:
  period: 14
ema:
  fast: 9
  slow: 21
sma:
  fast: 20
  slow: 50
macd:
  fast: 12
  slow: 26
  signal: 9
stoch_rsi:
  rsi: 14
  stoch: 14
  k: 3
  d: 3
atr:
  period: 14
bollinger:
  period: 20
  dev: 2.0
ichimoku:
  tenkan: 9
  kijun: 26
  senkou_b: 52

# cibles d'historique par TF (nombre de bougies locales à conserver)
history_target:
  "1m": 1500
  "5m": 1500
  "15m": 1500

