runtime:
  data_dir: /notebooks/scalp_data/data
  reports_dir: /notebooks/scalp_data/reports

  tf_list: [ "1m", "5m", "15m" ]
  age_mult: 5
  topN: 10
  refresh_interval_secs: 5
  backfill_limit: 1500

  risk_mode: "conservative"      # conservative | normal | aggressive
  exec_enabled: false
  html_port: 8888

  # === parallélisme backtest ===
  backtest_max_workers: 4        # nb de workers CPU (ProcessPool)
  backtest_chunk_size: 32        # nb de (pair,tf) par lot envoyé aux workers

  # === orchestrateur asynchrone ===
  auto_refresh: true
  refresh_every_secs: 30         # cadence worker refresh
  min_fresh_ratio: 0.8           # % cellules fraîches (DAT+OK) requis pour lancer backtest
  backtest_cooldown_secs: 120    # délai mini entre 2 backtests

  strategy_name: "ema_atr_v1"

  # Paramètres communs (frais/slippage identiques pour tous les modes)
  strategy_params_base:
    maker_fee_rate: 0.0002       # 0.02% (2 bps)
    taker_fee_rate: 0.0008       # 0.08% (8 bps)
    prefer_maker: true
    slippage_bps: 5.0            # 0.05%

  # Overrides selon le risk_mode
  strategy_profiles:
    conservative:
      ema_fast: 9
      ema_slow: 34
      lookahead_bars: 14
    normal:
      ema_fast: 12
      ema_slow: 34
      lookahead_bars: 10
    aggressive:
      ema_fast: 12
      ema_slow: 26
      lookahead_bars: 6