# engine/config/config.yaml
runtime:
  timeframe: "1m"
  refresh_secs: 5
  data_dir: "/notebooks/scalp_data/data"
  reports_dir: "/notebooks/scalp_data/reports"
  logs_dir: "/notebooks/scalp_data/logs"   # <— NOUVEAU

watchlist:
  top: 10           # TOP-N dynamiques
  score_tf: "5m"    # TF utilisé pour scorer (vol/volat)
  backfill_tfs: ["1m","5m","15m"]  # TFs à maintenir
  backfill_limit: 1500             # nb de barres à récupérer par TF

maintainer:
  enable: true
  interval_secs: 43200             # relance toutes les 12h
  seed_tfs: ["1m"]                 # TFs pour seed des stratégies EXPERIMENTAL
  ttl_bars_experimental: 120       # TTL en nb de barres pour EXPERIMENTAL