{
  "strategies": {
    "BTCUSDT:1m": {
      "name": "BASE_UNTESTED",
      "risk_label": "EXPERIMENTAL",
      "execute": false,
      "ema_fast": 9,
      "ema_slow": 21,
      "atr_period": 14,
      "trail_atr_mult": 1.5,
      "risk_pct_equity": 0.005,
      "last_validated": "2025-08-25T08:30:00Z",
      "ttl_bars": 120
    }
  }
}